# Generated by Django 3.0.2 on 2020-01-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('texte', models.TextField()),
                ('photo', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('tags', models.TextField()),
            ],
        ),
    ]
